### ISSUE TITLE
Rework `tb_client` packet memory management.

### ISSUE THREAD

**Issue by kprotty** [tigerbeetle/tigerbeetle#1226]
Currently, a `tb_client` user requests how many packets they want when creating a client instance. To submit a request, the user acquires a packet from the client and releases it when the request completes. Given there's a limit on inflight packets, `acquire_packet()` can fail which now introduces a synchronous failure path (packet errors are reported asynchronously after `submit()`).

Proposing an idea where the client leaves packet allocation to the user and `submit()` takes in packets intrusively / from any memory allocation. This allows the client user to allocate the packet along with any request data, control packet concurrency limits more flexibly, and move all client error handling to the `on_complete(packet, ...)` callback.

**Comment by jorangreef** [comment]
Thanks for opening this @kprotty and the write up.

Can you help me understand why/how the number of packets is decoupled from the number of messages? i.e. Why acquiring a packet may fail but not acquiring a message?

I take it that this change would also reduce surface area? i.e. It would remove the `acquire/release_packet` calls?

Finally, is there any way that we can get rid of packets entirely? What is the purpose they serve?

**Comment by batiati** [comment]
That's a nice simplification of tb_client's design.
@kprotty,  let me answer Joran's questions to check if my understanding of this proposal is correct, please correct me if you are thinking something different.

> Why/how the number of packets is decoupled from the number of messages?

Packets are a "bridge" in between the target language's thread+memory and the `tb_client`.
They act as a sync mechanism and a placeholder for the application's memory, in a way that we can have N:M messages -> packets. 

>  Why acquiring a packet may fail but not acquiring a message?

We tightly control the number of messages, e.g. they are only handled by the tb_client thread, instead of failing the thread will wait until a message becomes available before sending a new request.
Packets are exposed to the language threads, so they need to be acquired (with a lock) and submitted. This operation never waits but it can fail if no packets are available.

> It would remove the acquire/release_packet calls?

That's the beauty of this proposal.
We don't need to acquire/release packets from the tb_client anymore. It simplifies our API and gives a lot of flexibility to the language side to manage memory.

For example, using async calls in C#/Java, the language already needs to dynamically allocate a `Task` or `Future` to handle the completion. There's little benefit of having a pool of `Packet`s to acquire from. Instead, the language client could dynamically allocate a single-use `Packet` along other dynamically allocated structures such as the message payload, and the async completion handler.
One big advantage is completely removing the `concurrency_max` parameters, so the client can enqueue as many requests as it can allocate.
EDIT: On the other hand, as the `vsr` client by design never timeout, it can lead to OOM if the application keeps enqueueing requests when the client is disconnected. Maybe an upper limit isn't that bad.

> Is there any way that we can get rid of packets entirely? What is the purpose they serve?

They serve as a node of an intrusive linked list. This list is thread-safe and enqueues requests from multiple application threads (producer) for the `tb_client` single-threaded worker to send to the actual `vsr` client (consumer).
`Packet` also holds the application's memory pointer and other handlers that need to be freed/unpinned after conclusion.

I don't think we need to get rid of packets, but certainly, we can get rid of the fixed-size pool of packets.

**Comment by jorangreef** [comment]
Thanks for the explanation @batiati — @kprotty this will be great to do.

**Comment by matklad** [comment]
I _think_ this was done.
