### ISSUE TITLE
[Website] Blog subscription doesn't work in Firefox

### ISSUE THREAD

**Issue by emschwartz** [tigerbeetle/tigerbeetle#1335]
(Sorry this is probably not the best place to report this but...) Subscribing to email updates for the blog doesn't seem to work in Firefox. You can enter your email and click subscribe, and nothing happens.

I tried the same in Chrome and it does say it worked, though you don't get any kind of email confirmation.

**Comment by matklad** [comment]
cc @fabioarnold

**Comment by fabioarnold** [comment]
I can confirm that https://mailchi.mp/8e9fa0f36056/subscribe-to-tigerbeetle doesn't work in Firefox. It looks like Mailchimp is trying to load scripts with the wrong mime type (`"text/html"`) which Firefox seems to block. I will try to contact their support on Monday.

**Comment by fabioarnold** [comment]
Mailchimp just got back to us. The issue seems to be resolved. I can subscribe using the following steps:

1. Open your Firefox browser
2. Go to this URL: https://www.google.com/url?q=https://mailchi.mp/8e9fa0f36056/subscribe-to-tigerbeetle
3. Enter a valid email address like: someone@gmail.com
4. Click "Subscribe"

@emschwartz could you please confirm this works on your end, too?

**Comment by emschwartz** [comment]
Yeah, that works!
