### ISSUE TITLE
Batching example for C# seems wrong?

### ISSUE THREAD

**Issue by matklad** [tigerbeetle/tigerbeetle#1442]
We have the following as an example of batching in C#:

```cs
var BATCH_SIZE = 8190;
for (int i = 0; i < transfers.Length; i += BATCH_SIZE)
{
    var batchSize = BATCH_SIZE;
    if (i + BATCH_SIZE > transfers.Length)
    {
        batchSize = transfers.Length - i;
    }
    var segment = new ArraySegment<Transfer>(transfers, i, batchSize);
    createTransfersError = client.CreateTransfers(segment.Array);
    // error handling omitted
}
```

This seems wrong? If I am reading the docs correctly, `segment.Array` returns the entire array, not a subslice.

Which makes me think, should we perhaps be using spans in our API?

**Comment by matklad** [comment]
@batiati could you take a look at this?

**Comment by batiati** [comment]
Yes, the classic `Array` API isn't compatible with slices (or `ArraySegment` in this case). It would require copying the sliced segment into a new array or declaring one array per batch instead of slicing a bigger one.

> Which makes me think, should we perhaps be using spans in our API?

Sure! Using spans allows the application to optimize memory usage with reusable buffers, IIRC we didn't use spans from the beginning due to compatibility with older runtimes.

In C#, `Span`s are naturally more complicated because of lifetime restrictions, for more details there's an interesting guideline explaining how the C# compiler can keep track of slices (and situations where it can't):
https://learn.microsoft.com/en-us/dotnet/standard/memory-and-spans/memory-t-usage-guidelines#usage-guidelines

I created a PR converting the API to use slices, without breaking changes because arrays can be automatically coerced to slices.
https://github.com/tigerbeetle/tigerbeetle/pull/1443

Now the sample looks like

```diff
var BATCH_SIZE = 8190;
for (int i = 0; i < transfers.Length; i += BATCH_SIZE)
{
    var batchSize = BATCH_SIZE;
    if (i + BATCH_SIZE > transfers.Length)
    {
        batchSize = transfers.Length - i;
    }
-  var segment = new ArraySegment<Transfer>(transfers, i, batchSize);
-  createTransfersError = client.CreateTransfers(segment.Array);
+  createTransfersError = client.CreateTransfers(transfers[i..batchSize]);
    // error handling omitted
}
```
