### ISSUE TITLE
CI: Only run workflows when `src` is modified?

### ISSUE THREAD

**Issue by emschwartz** [tigerbeetle/tigerbeetle#1639]
What do you all think about running the test and build workflows only when certain directories are modified (such as `src` and maybe `tools`)?

It's not a big deal but if a PR only modifies the `docs`, it seems a little unnecessary to rerun all the tests and such (and right now some doc-related PRs' builds are failing because a previous commit broke the build)

**Comment by matklad** [comment]
I am strongly sure that we should not do this. Let me explain why!

> and right now some doc-related PRs' builds are failing because a previous commit broke the build

So this one _should_ be impossible. We use not-rocket science rule --- we _first_ run all the tests on a particular merge commit sha, and, only when the tests pass, we update the `main` branch to point to this already tested commit. 

So the failure here is not because a bad commit was merged, but because docked is flaky. 

But, overall, our CI should be top notch, fast and reliable, and, if it's not good enough for docs, it isn't good enough for everything else either. So, I'd rather use this as a push to improve our CI overall. 

If we start running parts of CI for particular changes, then:

* we increase the complexity of our CI setup
* we put presser to work-around, rather than fix, issues
* we relax not-rocket science rule, as we no longer have a strong guarantee that the tip of the main branch is fully tested. 

Let me loook into getting rid of that docker there...

**Comment by matklad** [comment]
https://github.com/tigerbeetle/tigerbeetle/pull/1642 should help with this particular CI failure

**Comment by emschwartz** [comment]
Makes sense!
