### ISSUE TITLE
thread 19356 panic: file system does not support Direct I/O

### ISSUE THREAD

**Issue by lil5** [tigerbeetle/tigerbeetle#1835]
Error:
```
$ ./tigerbeetle format --cluster=0 --replica=0 --replica-count=1 0_0.tigerbeetle
thread 19356 panic: file system does not support Direct I/O
```

I built from source on a linux workstation, the home user directory is encrypted with ecryptfs.

**Comment by sentientwaffle** [comment]
Hi @lil5!

Did you build with `-Dconfig=production`? If so, try building again without that flag.

We enforce Direct IO for the production config since it is critical for performance.
But I think ecryptfs is not compatible with direct I/O (since ecryptfs is a stacked filesystem that rewrites data).

(And by the way, the data files between `-Dconfig=production` and the default config are identical.)

**Comment by lil5** [comment]
I built with only the -build flag.

I'll close this issue, I'm moving to a MacBook Air & my vps works great with tigerbeetle ❤️. So I'm not going to put too much into this issue. 

Thanks, I advise any future viewers to just run tigerbeetle from an external ssd if you have the same issue.

**Comment by sentientwaffle** [comment]
Inspired by this issue, I implemented https://github.com/tigerbeetle/tigerbeetle/pull/1843 -- once that gets released, this should be simpler. You'll be able to just pass `--development` at runtime to a production binary to make it run without Direct IO.
