### ISSUE TITLE
256 or variable bit account ids

### ISSUE THREAD

**Issue by mankins** [tigerbeetle/tigerbeetle#1840]
I saw that `accountIds` were recently moved to `u128`, https://github.com/tigerbeetle/tigerbeetle/pull/1157 and I'd like to propose considering increasing the bits for accounts to at minimum `U256` or even have a custom variable bit encoding to allow for future growth. 

I'm new to this ecosystem and code base, but it looked like accountIds may be opaque ids with no arithmetic associated with them, so they could be represented in other ways.

My use case is to tie together accounts that are on a blockchain, for instance the XRPL (and Ethereum I think) which has 160 bit account addresses.

I could imagine wanting an arbitrary address id, "Matt's Account Number 1", so you could either allow storing that as a string, or store the `SHA-256` output as the address...hence the 256 bits request here.

I looked briefly and it seems that Zig doesn't have native 256 support, but perhaps there's a better struct anyway?

I'm happy to look into this further but before I got too far into it I wanted to post this in case there's already a path forward or will never be for other reasons.

Thanks

**Comment by matklad** [comment]
Hello @mankins!

Small things first: 

a) Zig supports `u256`, `u512`, `u42` and whatever else you want, so no problem here!

b) #1157 changed _balances_ to u128. I think IDs were always u128.

The general pattern here is that account ID should just be a random number, and any extra data should be associated with an account through some side table stored externally to TigerBeetle. So, on the blockchaing you can generate a random u128 id, and store a mapping u160 -> u128 there. 

Alternatively, we support small amount of custom data with accounts, through user_data fields: https://docs.tigerbeetle.com/reference/accounts#user_data_128. So you can use a combination of user_data_128 and user_data_64 to store a 160 bit XRPL account (while still using a random number for the TigerBeetle-side ID).

Hope this helps!

**Comment by mankins** [comment]
Hey @matklad thanks for the quick response.

> a) Zig supports u256, u512, u42 and whatever else you want, so no problem here!

Good to know about Zig, I'm new there and it wasn't clear, so thanks for that.

> The general pattern here is that account ID should just be a random number, and any extra data should be associated with an account through some side table stored externally to TigerBeetle. 

Would this be how traditional banks are expected to integrate? If I saw that field I'd be tempted to put in an accountId directly from my ledger. The extra layer of lookup/abstraction feels like a UUID so I kind of get that.

I guess it comes down to querying/filtering. If you can query via `user_data_128 = part1  and  user_data_64 = part2` then perhaps it's fine, although not for 256 bit use cases. It seems like it would make more sense to query by `accountId` when you're looking up an account. 

The filter interface doesn't seem to support filtering by user_data, so I'd have to lookup that mapping somewhere and then query tigerbeetle. I was hoping not to have three data stores.

**I guess the main question is, would there be a consideration to expand the account field, or is that a non-starter?**

**Comment by matklad** [comment]
>Would this be how traditional banks are expected to integrate?

Yeah! More general, the pattern is that TigerBeetle only deals with financial transactions, and for everything else you need to have a separate database. Most of the metadata is to be stored elsewhere. 

>I guess it comes down to querying/filtering.

Indeed! We do plan to add querying by `user_data`, though no ETA here. But in the fully general case (when your "native" ID is bigger than the user-data, or when you need user-data for something else), the pattern is that a side database looks up TigerBeetle ids from native IDS separately. 

One other option to consider is that, to go in one direction, you can cryptographically hash a u160 ID to u128 ID

---

But, in general, I think it is more or less set in stone that ids are u128. The _purpose_ of ID is not to store any specific data, but to be a unique random number. u128 is enough here. For any structured data, the intention is to use user data, side table (or, speculatively, blob storage, if we do that in TigerBeetle).

In _some_ cases you might cleverly re-use your existing IDs for TigerBeetle (if your id is <= 128 bit, or if one-way hashing is enough), but that is considered to be an optimization.

**Comment by mankins** [comment]
I see. I am still not in agreement here:

> u128 is enough here.

But understand your project has its own needs. Thanks for explaining.

**Comment by matklad** [comment]
>u128 is enough here.

To clarify, are you saying that `u128` is not enough specifically for providing random uniqueness to avoid collisions, or, more generally, that `u128` is not enough for purposes other than uniqueness?

**Comment by mankins** [comment]
With the caveat that I haven't gone deep in this and am just looking at this as a system integrator might to decide if I could build something with tb:

The reference externally has its own size and I'm not confident enough in something like SHA1 because of [this](https://shattered.io/). And so would prefer to keep the bits the same as they are on the external accounts, with the bonus of saving a lookup (which will in practice slash the transactions/second of the overall system even if TB is fast.)

For average things I think 128 bit randomness is likely fine, it's just the architectural concept of linking via random id instead of actual value for the account (an important if not key part of a financial transaction) that causes me to potentially bounce here. (I haven't given up yet, but that's where I am at the moment.)

**Comment by matklad** [comment]
Yes, this all sounds reasonable! There's indeed a tradeoff here between:

* using fixed-sized, rigid data structures for performance 
* providing flexibility & customization

So far, our design principle is that we favor simplicity on TigerBeetle's side and performance more than flexibility. Adding varsized data would be a pretty big architectural departure, and a bigger fixed-sized data is bound to not be enough for everybody. 

That being said, TigerBeetle is ultimately parametrized at comptime with a specific state machine, so building a separate copy of TigerBeetle with larger (but still fixed-sized) IDs would be possible. We might go the way of providing multiple flavors of TB in the future, but right now we are focused on our specific state machine. While it doesn't cover all use-cases, our idea is to nail a subset of use-cases perfectly, and then expand from that!

For performance concerns specifically, the "external ID -> TigerBeetle ID" mapping can be handled by the API gateway, and there should be multiple gateways, so this can be worked-around by adding more horizontal scalabilty. 

With this, I will close the issue, as I don't think there's any actionable here for us short term. 

Thanks for the discussion non-the-less, it's very helpful to have all these rationale spelled out so that it's easier to judge the tradeoffs.

**Comment by tomekmarchi** [comment]
> Yes, this all sounds reasonable! There's indeed a tradeoff here between:
> 
> * using fixed-sized, rigid data structures for performance
> * providing flexibility & customization
> 
> So far, our design principle is that we favor simplicity on TigerBeetle's side and performance more than flexibility. Adding varsized data would be a pretty big architectural departure, and a bigger fixed-sized data is bound to not be enough for everybody.
> 
> That being said, TigerBeetle is ultimately parametrized at comptime with a specific state machine, so building a separate copy of TigerBeetle with larger (but still fixed-sized) IDs would be possible. We might go the way of providing multiple flavors of TB in the future, but right now we are focused on our specific state machine. While it doesn't cover all use-cases, our idea is to nail a subset of use-cases perfectly, and then expand from that!
> 
> For performance concerns specifically, the "external ID -> TigerBeetle ID" mapping can be handled by the API gateway, and there should be multiple gateways, so this can be worked-around by adding more horizontal scalabilty.
> 
> With this, I will close the issue, as I don't think there's any actionable here for us short term.
> 
> Thanks for the discussion non-the-less, it's very helpful to have all these rationale spelled out so that it's easier to judge the tradeoffs.

Love that idea of flavors very exciting. I understand all points and it also may still make sense to offer a u64 variant too if it does provide better performance for those use cases. u128 sounds like a good general use case or most. However, I very much would like to entertain this idea of different flavors and since emerging financial markets are looking at larger ints (naturally) it would be great to have a version of TB specifically for maybe general purpose u256 as the default. From a post-quantum crypto perspective u256 is basically the minimum for that side of work.
