### ISSUE TITLE
Documentation questions

### ISSUE THREAD

**Issue by andreujuanc** [tigerbeetle/tigerbeetle#1860]
Hi, 

Amazing work have been put into this project! I really like it. 
While running some tests nodes I found a couple of issues that got my attention and wanted to report back:

## Issue 1
Running ` docker run -it --rm ghcr.io/tigerbeetle/tigerbeetle:0.15.3 format --cluster=0 --replica=0 --replica-count=1 --development 0_0.tigerbeetle`
Results in: `error: unexpected argument: '--development'`
Question: Was that flag removed? cos it's all around the .md files

## Issue 2
Running `docker run -v $(pwd)/data:/data ghcr.io/tigerbeetle/tigerbeetle  format --cluster=0 --replica=0 --replica-count=1 --development /data/0_0.tigerbeetle`  as per documentation
Results in: `error: PermissionDenied`
Solution: run the container with the `privileged` flag
Question: Why does the process need to run on privileged?

Thanks!

**Comment by sentientwaffle** [comment]
> Was that flag removed? cos it's all around the .md files

The opposite -- the docs are built from the main branch, which includes this flag, but we haven't released a build since the flag was added. It will be included in our next release, though.

You can ignore `--development` for now. Sorry for the confusion!

> Why does the process need to run on privileged?

IIRC this is because we require access to io_uring, which docker blocks access to by default.

**Comment by andreujuanc** [comment]
> IIRC this is because we require access to io_uring, which docker blocks access to by default.

Oh I see!  I was trying to do an experiment with docker and some lambdas :P
Thanks a lot for the quick response! Will do proper hosting to test it better :D
