### ISSUE TITLE
error: unexpected argument: '--development'

### ISSUE THREAD

**Issue by ItalicIntegral** [tigerbeetle/tigerbeetle#1861]
I am following instructions to try tigerbeetle on Linux Ubuntu Budgie 23.10.

However I am getting an error when trying to run the command below.
error: unexpected argument: '--development'

`./tigerbeetle format --cluster=0 --replica=0 --replica-count=1 --development 0_0.tigerbeetle
`

**Comment by sentientwaffle** [comment]
The docs are built from the main branch, which includes this flag, but we haven't released a build since the flag was added. It will be included in our next release, though. (I will remove the flag from the docs [shortly](https://github.com/tigerbeetle/tigerbeetle/pull/1862)).

You can ignore `--development` for now. Sorry for the confusion!

**Comment by sentientwaffle** [comment]
Docs are updated now: https://github.com/tigerbeetle/tigerbeetle/pull/1862
