### ISSUE TITLE
Are there any reproducible benchmarks with other databases that show a 1000x gain of the current technology?

### ISSUE THREAD

**Issue by mkornaukhov** [tigerbeetle/tigerbeetle#1926]
You claim to be three orders of magnitude faster than general purpose databases in some scenarios. Is there somewhere we can look at such benchmarks?

**Comment by jorangreef** [comment]
Thanks @mkornaukhov03!

To first understand (from first principles) how we designed TigerBeetle for three orders of magnitude more performance, please see our in-depth technical overview given at QCon SF: https://www.infoq.com/presentations/redesign-oltp/

This goes into how we redesigned the network protocol, storage engine and consensus protocol from the ground up, and gives a taste also of performance optimizations to come. I hope this gives you enough of a glimpse of the performance challenges and how TigerBeetle solves them.

Then, in terms of benchmarks, we have done several against cloud providers and open source databases, for our own understanding to see the impact of row locks and write contention on these databases. We're careful not to publish these (because benchmark wars!) but we did do a fun, respectful comparison against Postgres here: https://youtu.be/Wmjrb_HX7RA?t=99 where we give Postgres high end cloud hardware with NVMe, and then race against TigerBeetle running on a Raspberry Pi with micro SD card storage and mobile hotspot wifi. In the talk, some of the slides got cut off so you don't see the performance numbers as they run along the top of the screen, but in most of the races we're giving Postgres a few seconds of head start as well, and letting TigerBeetle catch it (or not!).

**Comment by rainychris** [comment]
https://github.com/kizzx2/tigerbeetle-benchmarks

**Comment by kizzx2** [comment]
https://github.com/kizzx2/tigerbeetle-benchmarks
