### ISSUE TITLE
Questions about get_account_balances

### ISSUE THREAD

**Issue by jkulubya** [tigerbeetle/tigerbeetle#2045]
When I follow the steps below, using my normal non-dev brain
1. Create new account with id x
2. Call `get_account_balances` x.

I expect to see a balance of zero, but get the error below when using the repl and and empty list when using the dotnet client.
```
> lookup_accounts id=2075911696222944204952185916219782546;
{
  "id": "2075911696222944204952185916219782546",
  "debits_pending": "0",
  "debits_posted": "0",
  "credits_pending": "0",
  "credits_posted": "0",
  "user_data_128": "285298181524112505011057082801545187073",
  "user_data_64": "171715390848712",
  "user_data_32": "0",
  "ledger": "100",
  "code": "21500",
  "flags": ["debits_must_not_exceed_credits","history"],
  "timestamp": "1717153910173162960"
}
> get_account_balances id=2075911696222944204952185916219782546;
Cannot get account balances: repl.LookupTransferResult.no_matching_results
```

Additionally, because balances are linked to transfers, calling `get_acocunt_balances` even when there are transfers posted to an account doesn't return a zero opening balance in results - only the balances after a transaction has been posted.

All of this is documented, but isn't a zero balance a balance? It feels like useful information is being thrown away.

Maybe what's lacking is automatically posting a transfer with the opening balance (zero or otherwise) of an account at creation, but I don't have the knowledge of TB internals to work out the pros and cons.

**Comment by batiati** [comment]
Hi @jkulubya, since the reply is almost identical, let me reproduce here the reply we talked about on [Slack](https://tigerbeetle.slack.com/archives/C043UG7QTHN/p1722058869810469).

> The `history` flag on accounts works by including the balance alongside each transfer that is executed, it gives us some interesting properties:
> 
> get_account_transfers and get_account_balances are complementary, and guaranteed to return 1:1 matches when the same filter is provided to both functions; So the application can join results from transfers and balances together by timestamp.
> The first "zeroed "balance of an account, does not have a corresponding transfer, so it's not expected to be returned by get_account_balances.
> And what may sound counter-intuitive, the most current balance of an account must be queried by lookup_accounts or query_accounts, since the last result of get_account_balances will not contain expired pending balances that were reverted automatically by the timeout (and not by a transfer posting/voiding it).
> 
> I want to add that all those query functions are part of a temporary API that will be replaced in the future by the proper query API. Some limitations might be a matter of time to implement, while others are the simplest design we could pick until we learn more about real use cases.
> If you could help us understand your use case for get_account_balances, it would be invaluable for us!

However you brought up a very interesting topic here:

>Maybe what's lacking is automatically posting a transfer with the opening balance (zero or otherwise) of an account at creation

Yes, it crossed our minds before, but we cannot be intrusive and create transfers on the user's behalf. This is especially true for the idempotency checks involving an `ID` field being generated by the cluster without any knowledge of how the [application encodes the IDs](https://docs.tigerbeetle.com/coding/data-modeling#id).

The simplest solution would be just inserting a history event without a corresponding transfer, but in this case, we found that ensuring a strong 1:1 relation between transfers and historical balances would be more valuable for the user cases we had in mind.

So please, it would be invaluable if you could help us understand your use case for get_account_balances.

**Comment by jkulubya** [comment]
To answer your question directly, the use case that brought me here was "display an account's running totals".

The problem is that the result for no transactions posted to account is the same as the account doesn't have the history flag set.

We figured that it's more likely that an account has no txns than is misconfigured (missing history flag), so for now we are just catching the null response and replacing it with an array with a single balance of zero.

So it's not a major blocker, and at this point we're happy enough to wait for the full query API
