### ISSUE TITLE
TigerBeetle Backup Recommendation/Best Practices?

### ISSUE THREAD

**Issue by shrsv** [tigerbeetle/tigerbeetle#2130]
Hello,

I was wondering - what are the recommendations around backing up TigerBeetle data?

Is it safe/sufficient to copy the data file(s) when the `tigerbeetle` program/process is running?

Or are there any dedicated command/mechanisms to perform data backup?

Any pointers about this - will be much appreciated.

Thank you

PS: I'm aware of replicas, but say I do not want to set them up yet. I just have a single experimental node, but would like to keep the data backed up for the future. I'm thinking about the TB equivalent of something like `pg_dump`

**Comment by matklad** [comment]
For single node, just copying the data file should be enough, yeah, although copying it while the process is actively writing to it would be incorrect. 

So:

* if you are on a file system which can atomically copy a file, then use that
* otherwise, you need to stop the node, copy the file, and restart the node
   * but this could be made faster by, for example, rsyncing the file while the node is running, stopping it, and then rsyncing just the diff.

**Comment by shrsv** [comment]
Got it, that makes sense, thanks for the clarification!
