### ISSUE TITLE
Questions about Query API and T-Accounts

### ISSUE THREAD

**Issue by wyalves** [tigerbeetle/tigerbeetle#2161]
Hello, Tiger Beetle team!

Ever since I discovered Tiger Beetle through ThePrimeagen, I've been intrigued by the possibilities it offers. We are currently considering using it in our high-performance banking services at work.

Bu I do have a few questions:

1. I've noticed mentions of the new "Query API" in other issues and perhaps in the documentation as well. Is there a roadmap or backlog available that outlines the capabilities this new API will provide?
2. Since T-Accounts create double entries for every transaction, does this mean I need to create and store a new account for every transfer received or sent to an account belonging to another bank's customer? Do you recommend any specific pattern for handling situations like these?

**Comment by batiati** [comment]
Hello there @wyalves! Bem vindo à comunidade TigerBeetle! :brazil: 

Thanks for your interest and for the great questions.

> I've noticed mentions of the new "Query API" in other issues and perhaps in the documentation as well. Is there a roadmap or backlog available that outlines the capabilities this new API will provide?

1. Yes, we often refer as "Query API" the set of features that will replace the stopgap functions we introduced, like `query_transfers` and `query_accounts`.
We don't have an exact ETA, but we have a **draft document** that details what we aim to support.
https://github.com/tigerbeetle/tigerbeetle/blob/batiati-query-execution/docs/internals/queries.md
Please note that this document is accurate about "what", but it may be outdated about "how"! So please take it with a grain of salt!

> Since T-Accounts create double entries for every transaction [...]

2. (a) The way double entry works on TigerBeetle is that each transfer must have a "debit" and a "credit" account. It has the "double-entry" effect since it changes atomically two balances at once, but physically it's a single transfer. Different from traditional accounting (paper and pencil), which would require two equal movements on each account, but on opposite sides of the "T" chart (debit/credit).

>  [do] I need to create and store a new account for every transfer received or sent to an account belonging to another bank's customer?

2. (b) When you receive money from an external entity, typically, it means that the money was credited to the customer's account and *debited* from a "treasury" or "custody" account (holding the customer's money is a liability for your bank).
The same (but the opposite) when the customer transfers money to an external entity, it's debited from their account and credited into yours (so it decreases the liability).
You may represent it as a single account for all customers or an account per external bank if that makes sense for your business.

**Comment by wyalves** [comment]
I see. _Obrigado_ for the answer!

I have one last question: As described in the documentation, "each TigerBeetle replica stores all data inside a single file, called the data file." Since transfers cannot be deleted after creation, if the data file of a replica grows too large, would I need to manually take down that replica and start it over with a new data file? Would this be a safe procedure, or is it something I should not do?

**Comment by batiati** [comment]
> if the data file of a replica grows too large, would I need to manually take down that replica and start it over with a new data file?

No, the data file is supposed to ever grow, and replacing it with an empty file would only reduce availability and possibly lead to data loss... at the best hypothesis, it will trigger the repair process to rebuild the entire file from other replicas.

Currently we don't have an archiving feature planned, although we might offer some storage tiering in the future, where cold data can be moved to other layers.

**Comment by wyalves** [comment]
Got it, thanks! We should start the first tests soon.
