### ISSUE TITLE
From 10ms batches to 12s batches with Go client

### ISSUE THREAD

**Issue by eatonphil** [tigerbeetle/tigerbeetle#226]
I am testing out the Go sample code here: https://github.com/tigerbeetledb/tigerbeetle-go/pull/17/files.

Both inside Docker and outside I get the same behavior:

```
info(message_bus): connected to replica 0
Started batch            0               2022-10-26 21:44:06.340125972 +0000 UTC m=+15.662152284
Done batch               0               2022-10-26 21:44:08.453414819 +0000 UTC m=+17.775441135                 2.113288975s
Started batch            8191            2022-10-26 21:44:08.456587344 +0000 UTC m=+17.778613656
Done batch               8191            2022-10-26 21:44:10.539311391 +0000 UTC m=+19.861337710                 2.082724166s
Started batch            16382           2022-10-26 21:44:10.542538624 +0000 UTC m=+19.864564942
Done batch               16382           2022-10-26 21:44:12.645896921 +0000 UTC m=+21.967923240                 2.10335843s
Started batch            24573           2022-10-26 21:44:12.649172381 +0000 UTC m=+21.971198694
Done batch               24573           2022-10-26 21:44:14.762033368 +0000 UTC m=+24.084059683                 2.112861058s
Started batch            32764           2022-10-26 21:44:14.765275593 +0000 UTC m=+24.087301906
Done batch               32764           2022-10-26 21:44:16.856221753 +0000 UTC m=+26.178248067                 2.090946233s
Started batch            40955           2022-10-26 21:44:16.859746031 +0000 UTC m=+26.181772343
Done batch               40955           2022-10-26 21:44:30.909707893 +0000 UTC m=+40.231734212                 14.049961935s
Started batch            49146           2022-10-26 21:44:30.912962798 +0000 UTC m=+40.234989121
```

Where batches start out performing reasonably and then get an orders of magnitude slower after around 40,000 transfers. These ones show up as 2s and 14s but that's because TigerBeetle debug mode is on. Without them they are more like 10ms and then jump to 10s per batch.

Here's how I run the server (commit 3fb0b76199efbbb7acc7b14c8532ab7bbb738100):

```
rm -rf 0_0.tigerbeetle && ~/tb/tigerbeetle/tigerbeetle format --cluster=0 --replica=0 0_0.tigerbeetle && ~/tb/tigerbeetle/tigerbeetle start --addresses=3000 0_0.tigerbeetle > log 2>&1
```

The log is attached.

[slow_tb_log.txt](https://github.com/tigerbeetledb/tigerbeetle/files/9873932/slow_tb_log.txt)

**Comment by sentientwaffle** [comment]
The slowdown happens when we commit op 8, which (with the default configuration of `lsm_batch_multiple=4`) is the first op which needs to prefetch against the on-disk levels (just level 0). For some reason the prefetch stage is taking far longer than expected.

**Comment by sentientwaffle** [comment]
- The slow op encountered is `create_transfers`.
  - The step that is taking too long is the commit's prefetch.
  - (The value cache isn't helping because we are checking for ids that exist — we have to read from the levels.)
- The reads are all hitting the grid cache, so it isn't IO.
- The groove's prefetch concurrency is determined by `Grid.read_iops_max`.
- `Grid.read_iops_max` is currently 15.
- Because we (correctly!) defer grid cache lookups to the next tick (rather than handling them synchronously) we can only perform 15 lookups per tick.
- `config.tick_ms` is 10, so we tick 100 times per second.
- That comes out to `8191 / (100 * 15) = 5.46` seconds. Multiply by 2 because we need an index block and a filter block each time.

To fix this, `Grid.tick()` should return a `bool`: "whether any work was accomplished by this tick call".

Then in `Replica.tick()` we keep calling `Grid.tick()` until it stops returning `true`. That way we can "synchronously" handle as many cache hits as possible within a single IO tick — without risking the stack overflowing by _actually_ handling them synchronously.

**Comment by jamii** [comment]
With the branch above I'm seeing 1.32s for compacting 532415 transactions. Enough to fill one table on level 0 (64mb / 128 bytes = 524288 transactions). 

Compaction works one 64kb data block at a time, serializing all the reads. So compacting the immutable table into level 0 takes 64mb/64kb = 1024 reads and 1024 writes. If we ballpark 100us read/write latency, that gives us a lower bound of ~200ms per table compacted. This doesn't explain all of the latency, but it is by itself enough to totally blow our latency budget.

It seems from the [cpu profile](https://gist.githubusercontent.com/jamii/0962c9cf5db6b3062d9c3f2c10ee283f/raw/f38365c30f104b5d79b878b31410631d8e88c4b9/gistfile1.txt) that there is also a substantial amount of cpu work involved in compaction.

**Comment by matklad** [comment]
I am not entirely sure whether this is fixed or not, but, if it is not, we should come up with a fresh benchmark here anyway.
