### ISSUE TITLE
Atomic TB + postgres transaction 

### ISSUE THREAD

**Issue by hillac** [tigerbeetle/tigerbeetle#2276]
Is it possible to put TB inside some kind of pg extension so that a single atomic transaction can mutate TB and pg? I don't really know enough about db's to know if this is a silly question. It would just be quite nice for applications that need atomicity with both transactions and general purpose tables.

Maybe something as simple as an extension that does a 2 phase commit to an external TB instance? Although I guess that may as well be an interface in the application itself.

I imagine getting full MVCC across pg and TB would be near impossible given the completely different data models.

**Comment by matklad** [comment]
That's sort of a vague question, but the answer needs to be specific to each setup!

In general, if you need atomocity across TB (OLTP) and PostgreSQL (OLGP), you might be better of handling everything in PostgreSQL. TigerBeetle exists because it is faster than PG for a specific use-case. If you put PostgreSQL on a hot-path, you won't be able to take advantage of TigerBeetle performance.

What you want to do is to handle transaction in TigerBeetle, and only in TigerBeetle. But you could poll TB from your OLGP and react to the current state of the ledger. 

See https://docs.tigerbeetle.com/coding/system-architecture

**Comment by hillac** [comment]
Thanks! I'll look into the polling. My reason was some transactions need to be atomic across both, but the majority can be just TB and take advantage of the speed.

**Comment by matklad** [comment]
@hillac ah, sorry, I missed the "_some_" aspect here. Indeed, if you only need _some_ transactions to be atomic with Postgress, that is reasonable. 

I think the way to implement this would be through some kind of two-phase commit protocol. On the TigerBeetle size, you could "prepare" a transaction by submitting a linked chain of pending transfers: https://docs.tigerbeetle.com/coding/two-phase-transfers/. 

We should document these better though!
