### ISSUE TITLE
Working on a Haskell client

### ISSUE THREAD

**Issue by agentultra** [tigerbeetle/tigerbeetle#2361]
Hello Tigerbeetle team!

I've been curious to try out the project for some time and started writing some Haskell bindings but ran into some trouble with the official C client using the non-standard 128-bit unsigned integers.

I'm sure there are reasons for choosing to use this type an an API meant for FFI clients to be built on but Haskell 2010's FFI can't marshal data larger than unsigned 64-bit integers.

I was thinking I may have to write a shim library over `tb_client.h` in order to address the issue. There are Haskell libraries supporting unsigned 128-bit integers but I'd have to add another layer to pass the pointers across and re-assemble the `tb_uint128_t` on the C side. Is this also what the Go client does (and why GCC is required to use it)?

I don't suppose there's the possibility of a backwards compatible change to arrange for the `tb_uint128_t` type to be a struct of two `uint64_t`? That would make things easier.

Anyways, not looking to report a bug here, just a hacker looking for some guidance on how to write an FFI wrapper for your official client library on platforms with FFI's that don't support marshalling to non-standard types.

**Comment by batiati** [comment]
Hello @agentultra!
First things first, it's fantastic to hear that you're working on a Haskell client!!!! 
Please join our [Community Slack](https://join.slack.com/t/tigerbeetle/shared_invite/zt-21xk62q7l-p~~G7~H01zQb88rQn7tWfQ), where we have a dedicated channel for client implementations!

Actually, `tb_uint128_t` is an alias for the standard [` __int128`](https://gcc.gnu.org/onlinedocs/gcc/_005f_005fint128.html) type, which has well-defined and stable ABI, but indeed, unsupported in many programming languages (none of the official clients have native 128-bit support for FFI).

The good news is that we don't need to change the `tb_client` library to expose this type differently, but instead, the FFI consumer can define how it should be marshaled. 
For example, take a look at how the [C# client defines UInt128](https://github.com/tigerbeetle/tigerbeetle/blob/ecb8ef19935cdf268a2d35c5188f7c4fbadbe627/src/clients/dotnet/TigerBeetle/UInt128Extensions.cs#L14-L29) backed by a fixed-length array of 16 bytes.
It's up to you to better represent the FFI binary in Haskell, for example, by using a custom type, a standard BigInteger/UUID, or even as a pair of 64-bit integers or an array of bytes (like the Java client does).

Regarding the Go client, it requires CGO because we link with the static library (no dynamic library is loaded during runtime).

**Comment by agentultra** [comment]
Thank you for the awesome, helpful reply.

I will definitely check out the Slack channel, cheers.

There is a library with some types to represent `uint128_t` types in Haskell (as a struct, basically, with hi + lo 64bit members. Comes with everything it needs to marshall the values. The limitation is the FFI in Haskell. I may need to write a shim library to pass pointers around... hopefully not a huge overhead.

Thanks again, and have a great one!
