### ISSUE TITLE
Zig build creates old version

### ISSUE THREAD

**Issue by jasonfiammetta** [tigerbeetle/tigerbeetle#2575]
Following the steps to build from source suggested in [the docs](https://docs.tigerbeetle.com/quick-start/#build-from-source):
```
./zig/download.sh
./zig/zig build
./tigerbeetle version
```
on macos gives this
```
$ ./tigerbeetle version
TigerBeetle version 0.0.1+a30cab9
```

I've confirmed it's downloading the right file from [the release page](https://github.com/tigerbeetle/tigerbeetle/releases/latest/download/tigerbeetle-universal-macos.zip), and using curl works fine.

**Comment by matklad** [comment]
This is intentional behavior --- build from source is tagged as 0.0.1, a development version, by default, to avoid accidentally mixing up production and development binaries. If you care about specific version of TigerBeetle you probably want to use a pre-built binary from the releases page.

You can use various `-D` flags to set specific version during build (see build.zig), but that's intentionally not documented, as its tricky to do correctly, and, at this point, we intend to fully support only the pre-built binaries!

**Comment by jasonfiammetta** [comment]
Oh thanks, that's good to know. Might want to add that as a note to the docs, or maybe just exclude building from source from the Quickstart section.

**Comment by matklad** [comment]
> or maybe just exclude building from source from the Quickstart section.

Yeah, that's actually done in 

https://github.com/tigerbeetle/tigerbeetle/pull/2521/files#diff-298e509e87a2e9501cb8f763fb811a38b5a10fb14ab30f4ef55ce7f0c58821b3R29

but we are waiting for a certain stack of yaks to get shaved before deploying that!
