### ISSUE TITLE
Feature Request: Transfer Queries

### ISSUE THREAD

**Issue by adrianhopebailie** [tigerbeetle/tigerbeetle#28]
It would be great to be able to fetch a list of transactions from TigerBeetle.
Possible filter criteria:
 - By debit account
 - By credit account
 - By amount range
 - By user data (e.g. find all transfers with the same external transaction reference)

Prob need to limit result count and always have a timestamp range.

**Comment by mjbrichards** [comment]
I don't think that you'd want to include a timestamp range for (some?) queries by user data. For instance, if I wanted to see all the ledger entries relating to a transfer ID, I wouldn't care when they were...

**Comment by adrianhopebailie** [comment]
@mjbrichards that is fair but the start time that you query for may be limited by the amount of data TB has in memory. It would be quite expensive to go and scan the transfers that have been persisted to disk and dropped of the in-memory hash-table.

For those kinds of queries I expect we'd drain the data from TigerBeetle into a big data store optimised for queries like that

**Comment by mjbrichards** [comment]
I agree that you'd want to organise your storage like that, but imo that shouldn't be visible to the user of the API. They should just be able to say, gimme this stuff, and leave it to TB how to retrieve it...

**Comment by jorangreef** [comment]
Thanks @adrianhopebailie for these use-cases (and hello to @mjbrichards).

We are thinking of secondary indexes to support fast queries for transfers by:

- `account_id` e.g. get all transfers that debited or credited an account,
- `user_data` e.g. get all transfers that relate to an external entity (many-to-one, where many transfers may all relate to a single external entity),
- `code` e.g. get all transfers that served a user-defined chart of accounts purpose (all "settlement" transfers), and
- `expiry` e.g. get all transfers that expired.

These indexes would be sorted by transfer timestamp, to allow queries to be further refined by inclusive `min..max` timestamp range (even open-ended on either side), and by the number of desired results, and these secondary index queries could also be set intersected, e.g. get all transfers with `code=C AND user_data=UD`, so that querying TigerBeetle would be pure set theory intersections, nice and simple and fast.

Accounts, and Commits would have similar indexes.

For cooler data that has drained to TigerBeetle's local disk storage (before draining out over the network to archive storage), we would like to keep the implementation invisible to the user. I think we can come up with something that makes the hierarchical storage and indexing work well.

From here, some questions:

- Do we need to distinguish between `debit/credit_account_id` when indexing? Is it okay to just return all transfers that touched an account?

- What would be the use-cases for an amount range query? Fraud queries? Anything else? How essential is it for this to be in TigerBeetle? Would the secondary indexes above be enough to "get into the ball park" to support this, with in-application filtering by amount? The reason I ask is that an index on the amount would be more dimensional, and would need a different indexing structure. We can't use our convenient immutable append-only timestamp order, we would need to keep sorting the index, so if we can avoid it that would be great, but if we need it, that's not a problem. We do need a similar structure for another internal component.

**Comment by mjbrichards** [comment]
I'm assuming that the entries in TigerBeetle will represent the system of record relating to transfers in the switch. Information (much of which will be additional to the information that TB holds) will be extracted by the switch for reporting purposes, and broadly speaking we will want to be able to source the answer to queries from the reporting system if we can, So TB will need to answer system-of-record queries about transfers, but not any other kind of query: that should be handled by reporting. I kind of think that means that TB will need to include a feed to reporting (for instance, by putting events on a queue when it makes changes.)

So I guess the question about this is: what are the legitimate areas of interest in the system of record? For me, I think that rules out amount range queries. Presumably enquiries about transfers would need an enquiry by transfer ID.

We probably also need to think about how we would expect to handle new requests. Coincidentally, I have an example. Mowali want to be able to report on transfers which have spent more than a specified interval between prepare time and commit time. Would we expect that this would be handled from the reporting database? I'm OK with that, but I guess we need to be explicit about it...

**Comment by kakserpom** [comment]
Why mix OLTP and OLAP? TigerBeetle is a great thing for OLTP. Ledger entries are immutable. Why not just replicate transfers to an OLAP database like Clickhouse? So then you can have all fun you want with your data without affecting your OLTP performance.

**Comment by jorangreef** [comment]
@kakserpom thanks for the question.

TigerBeetle is not only about safety, and performance, but also about operator experience, having a first-class ledger database experience out of the box, with support for the sweet spot of 80% of common queries. We do also optimize for performance, because we can trade this for usability.

This also makes sense from the point of view of where hardware is going—disk write bandwidth is increasing relative to CPU, so that indexes are becoming cheaper than they used to be to maintain, enabling query engines in OLTP databases to become more powerful.

**Comment by matklad** [comment]
We have basic query capabilities now. They can be extended, but that'll be a separate issue.
