### ISSUE TITLE
VSR: Replace "commit" command with ping/pong

### ISSUE THREAD

**Issue by sentientwaffle** [tigerbeetle/tigerbeetle#329]
- Get rid of `commit` messages — use pings/pongs instead.
- Primary puts commit information into the ping message.

**Comment by matklad** [comment]
DJ and myself looked into this today, this is slightly tricky. The following things are true as of today:

* both pings and commits are broadcast
* pings carry timestamps which are used to compute cluster time and thus pings are latency sensitive
* commits carry view numbers, which are a useful to make sure everyone is up-to-date wrt current view
* we don't sent messages which carry view information unless the view is persisted to disk, as, for some messages, going back on our view commitment breaks consensus

So, if we naively merge commits and pings, pings would sometimes be skipped due to view not being on disk yet, breaking our clock synchronisation. 

Our options:

- remove view from commits, as I don't think we need it for commit per-se. Loosing view broadcast is not great though!
- move actual commit to pings, but keep old commit message just to broadcast view. Doesn't actually improve anything, as we still have two message types
- add an exception for pings for "don't send message if the view is not durable" logic. I _think_ this should be correct, as pings are not a VSR message and nothing would break even if the replica then goes back on its view. Feels somewhat inelegant though
- status quo. Pings are already overloaded a bit to communicate time between replicas, and current view to the client, adding commits to the mix would not make things simpler (though, it would improve efficiency a bit)

**Comment by sentientwaffle** [comment]
In my current work (not yet PR'd):

- `ping` is a separate message type from `ping_client`
- `pong` is a separate message type from `pong_client`
- `ping`s are now used as heartbeats — in their absence replicas decide to begin SVC, which may lead to a view change. (The extra `ping` step helps ensure that asymmetric partitions don't cause problems for an otherwise-healthy cluster).

As part of the heartbeats, `ping`s include a `view` anyway, so I think we are back to combining `ping` + `commit`.

**Comment by sentientwaffle** [comment]
Nevermind, I tried this out & decided I still prefer the status quo.

Ping/pong is "normal replica <-> normal replica" 
Commit is "primary normal replica -> backup normal replica" 

The _can_ be combined, but we wind up with different "types" of ping (one with commit data and one without), with the same `command`, and I think its cleaner to avoid same-`command` variants like that when possible (like we do with `ping` vs `ping_client`).
