### ISSUE TITLE
Shrink table_mutable

### ISSUE THREAD

**Issue by jamii** [tigerbeetle/tigerbeetle#490]
Currently the load factor is set to 50%, which is fairly wasteful. Unfortunately `value_count_max` is just below a power of two, so even load factors up to 99% result in https://github.com/ziglang/zig/blob/6d44a6222d6eba600deb7f16c124bfa30628fb60//lib/std/hash_map.zig#L876 rounding up the allocation size to an effective load factor of just under 50%.

**Comment by jorangreef** [comment]
For hash tables that do linear probing, a load factor of 50% is important to avoid excessive collisions, clustering and probing.

We could do 60% or perhaps 70% I think, given that Zig's implementation is pretty good, but then it's risking clustering and more CPU-intensive probing, so we should then also verify that these load factors don't cause excessive probing.

**Comment by sentientwaffle** [comment]
For object trees only:

If we're willing to pay an extra indirection cost + complexity, the hash map could be `timestamp → usize` instead of `Value (implied timestamp key) → void`, and then store the values themselves in a fixed-capacity arraylist, indexed by that `usize`. We still pay the 50% hashmap load factor overhead, but we would be paying it for `@sizeOf(timestamp) + @sizeOf(usize)` instead of `@sizeOf(Value)` — 16 bytes vs 128 bytes.

**Comment by sentientwaffle** [comment]
> store the values themselves in a fixed-capacity arraylist

Which we could then sort in-place and swap with the immutable table's arraylist when we transition mutable → immutable to avoid copying all of the values out.

**Comment by jorangreef** [comment]
This is a neat trick—and a "super idea" for both reasons.

**Comment by matklad** [comment]
table mutable is no longer a hash table
