### ISSUE TITLE
Store/query user defined  custom types/entities.

### ISSUE THREAD

**Issue by ansarizafar** [tigerbeetle/tigerbeetle#67]
I understand TigerBeetle has been designed from ground up for financial transactions but it would be great If somehow we can also store/query user defined  custom types/entities (users, products etc.)  as  If entities Ids and other data is stored in any other database  then we can loose that data because of disk failure or any other issue as other databases are not as fault tolerant as TigerBeetle is, In that case whole system will become useless.  with the ability to store user define entities/types TigerBeetle  will become a complete database and a game changer with  all other innovative and novel features. I request you to please consider this proposal.

**Comment by jorangreef** [comment]
Thanks @ansarizafar we hear you!

Stay tuned. TigerBeetle has actually been designed from the ground up to support custom types and custom business logic, since it's built around the concept of a "replicated state machine". Take a look at `src/state_machine.zig` for what could be customized. However, this will be some time out, and not something we'll address immediately as we need to get TigerBeetle to production first. But it is something we're actively building in to TigerBeetle's underlying design, and the design is certainly better for it.

Thanks again for the feedback.
