### ISSUE TITLE
Types: Move Commits into Transfers, rename `reserved/accepted` to `pending/posted`, rename `unit` to `ledger`, and add `ledger` to Transfer

### ISSUE THREAD

**Issue by koekiebox** [tigerbeetle/tigerbeetle#68]
Currently a 2-phase Transfer makes use of the `Commit` struct during the commit operation. Making use of the `Commit` is not required during `commit` as the `Transfer` struct already hosts all the necessary types. 

The commit function signature `commit_transfer(self: *StateMachine, c: Commit)` should therefore be replaced by `fn commit_transfer(self: *StateMachine, t: Transfer)`.

In addition, removing/merging the `Commit` would also mean the `commit()` operation would benefit from existing `Transfer` features such as linked events.

## `Commit` struct to be merged with `Transfer`
```zig
pub const Commit = packed struct {
    id: u128,
    /// Reserved for accounting policy primitives:
    reserved: [32]u8,
    /// A chart of accounts code describing the reason for the accept/reject:
    code: u32,
    flags: CommitFlags,
    timestamp: u64 = 0,

    comptime {
        assert(@sizeOf(Commit) == 64);//Only drawback is the Transfer being 128 bits, but this is a non-issue
    }
};

pub const CommitFlags = packed struct {
    linked: bool = false,
    reject: bool = false,
    preimage: bool = false,
    padding: u29 = 0,

    comptime {
        assert(@sizeOf(CommitFlags) == @sizeOf(u32));
    }
};
```

## `Transfer` struct
```zig
pub const Transfer = packed struct {
    id: u128,
    debit_account_id: u128,
    credit_account_id: u128,
    /// Opaque third-party identifier to link this transfer (many-to-one) to an external entity:
    user_data: u128,
    /// Reserved for accounting policy primitives:
    reserved: [32]u8,
    timeout: u64,
    /// A chart of accounts code describing the reason for the transfer (e.g. deposit, settlement):
    code: u32,
    flags: TransferFlags,
    amount: u64,
    timestamp: u64 = 0,

    comptime {
        assert(@sizeOf(Transfer) == 128);
    }
};
```

**Comment by sentientwaffle** [comment]
When a client commits a transfer, which fields of a `Transfer` would it actually send? Would it only populate the `id` plus whatever flags (previously part of `Commit`) are relevant, and leave the other `Transfer` fields zeroed?

**Comment by koekiebox** [comment]
> When a client commits a transfer, which fields of a `Transfer` would it actually send? Would it only populate the `id` plus whatever flags (previously part of `Commit`) are relevant, and leave the other `Transfer` fields zeroed?

Yes @sentientwaffle . :100:.

**Comment by jorangreef** [comment]
Thanks @koekiebox for getting this going!

> When a client commits a transfer, which fields of a Transfer would it actually send? Would it only populate the id plus whatever flags (previously part of Commit) are relevant, and leave the other Transfer fields zeroed?

- The `id` for the 2nd-phase transfer (previously the Commit) would be unique so it doesn't conflict with the 1st-phase transfer in the dedupe check we do in the state machine.
- The 2nd-phase transfer would then need to reference the 1st-phase transfer ID, putting this in the 128-bit `user_data` field.
- This leaves the 256-bit `reserved` field free to store the hashlock `preimage`.

We should all think through how we want to indicate that the 2nd-phase transfer is a commit? We need an extra flag to indicate that somehow and we need to come up with a good name. We need to have `reject` but perhaps this could become `two_phase_commit_reject` and then we could bring back the implicit accept with `two_phase_commit_accept`? So just two flags, either of which indicates that it's the 2nd-phase and then what the decision was.

**Comment by jorangreef** [comment]
So the 1st phase will set `two_phase_commit` to indicate that the two-phase commit protocol is in play, and then the 2nd phase will set either `two_phase_commit_accept` or `two_phase_commit_reject`.

**Comment by jorangreef** [comment]
@koekiebox @sentientwaffle @ifreund what are your thoughts?

**Comment by jorangreef** [comment]
What other options can we come up with?

**Comment by sentientwaffle** [comment]
Could the wire protocol just keep using commits (or commit-like objects) and translate at the server? Commits are much smaller than transfers, so it would keep the protocol slimmer.

**Comment by jorangreef** [comment]
> Could the wire protocol just keep using commits (or commit-like objects) and translate at the server? Commits are much smaller than transfers, so it would keep the protocol slimmer.

Yes, that is a downside.

On the upside, we then have everything aligned to 128-bytes (accounts, transfers, headers), avoid the complexity of doing the conversion at the server (which is a memcpy plus additional buffer scratch space I think to translate from `Commit` to `Transfer`?), and keep the 1-to-1 mapping of data to API that we have.

It would then be a total overhead of 256 bytes to do two-phase commit vs 192 bytes as before.

**Comment by sentientwaffle** [comment]
> It would then be a total overhead of 256 bytes to do two-phase commit vs 192 bytes as before.

:+1: That sounds reasonable; I expected it to be a larger difference.

**Comment by jorangreef** [comment]
Cool, me too, it's a 33% extra overhead when compared like that (significant). It feels bigger when looking at the `Commit` struct alone, without taking the first phase into account, i.e. going from 64 bytes to 128 bytes is a 100% extra overhead or doubling (severe).

**Comment by jorangreef** [comment]
So I think I have come up with better naming for `reserved/accepted` and for the corresponding two-phase transfer flags, that:
* maps better to industry use, and that
* won't confuse DistSys engineers into thinking we're doing "two-phase commit" consensus also through this feature. VSR does its own form of two-phase commit at a lower layer, so the present naming is overloading the term, and we had a question about this in our Discord group.

Let's follow the [credit card terminology of `pending/posted`](https://www.investopedia.com/terms/c/credit-card-posting.asp) instead, and then for the flags we do the same again using the [terminology of voiding or posting](https://www.investopedia.com/terms/v/void-transaction.asp) a pending transfer.

The semantics would be that:
* transfers post by default (updating the `posted` balance of the Dr/Cr accounts immediately), unless
* a transfer has a flag indicating it's `pending`, in which case we only modify the `pending` balance of the Dr/Cr accounts.
* a `pending` transfer can be posted by setting `posting` as a flag on a second transfer that references the `id` of the first`pending` transfer via the `user_data` field on the second transfer, to move the amount from the `pending` balances of the Dr/Cr accounts to the `posted` balances, and similarly
* a `pending` transfer can be voided by a `voiding` transfer with this flag set.

We then rename the Account `debits_reserved/accepted` and `credits_reserved/accepted` to `debits_pending/posted` and `credits_pending/posted` accordingly.

**Comment by jorangreef** [comment]
Implementing this feature of folding Commits into Transfers also has a little curve ball, because at present we dedupe the Commit like this:
```zig
if (self.get_commit(c.id)) |exists| {
    if (!exists.flags.reject and c.flags.reject) return .already_committed_but_accepted;
    if (exists.flags.reject and !c.flags.reject) return .already_committed_but_rejected;
    return .already_committed;
}
```
This works because the Commit has the same ID as the Transfer it's committing. Whereas now, the second transfer will need a unique ID but set the `user_data` to that of the first transfer. The curve ball is that, at present, we only have hash map indexes on the primary ids. The LSM-Forest will allow us to query by `user_data` later. In the interim, I propose we hack it by mutating the first transfer to set `posting` as well when it's committed.

**Comment by jorangreef** [comment]
While we're making these type changes, I propose we also make a few improvements for more orthogonality:
* Rename `unit` to `ledger` so that users can use `ledger` also in a broader way for multi-tenant isolation (and it makes sense to keep the actual currency unit alongside the metadata for the ledger in an external object/sql database as Rafiki is already doing, so this field is really more broadly about a ledger),
* decrease `flags` in Account and Transfer from u32 to u16, so that we can
* increase `ledger` from u16 to u32 for more ledger/currency support, and
* add `ledger` to Transfer (for more safety, to enforce that transfers may only affect accounts in the same ledger).

**Comment by jorangreef** [comment]
So our Account is going to look a little friendlier and more intuitive for anyone familiar with the distinction between pending/posted transfers:

```zig
pub const Account = packed struct {
    id: u128,
    user_data: u128,
    reserved: [48]u8,
    ledger: u32,
    code: u16,
    flags: u16,
    debits_pending: u64,
    debits_posted: u64,
    credits_pending: u64,
    credits_posted: u64,
    timestamp: u64 = 0,
};
```

Also, just to document a decision from last year, the reason we put `flags` after `{user_data, reserved, ledger, code}` is so that these fields are contiguous and can be reinterpreted for future features based on `flags`.

**Comment by jorangreef** [comment]
```zig
pub const Transfer = packed struct {
    id: u128,
    debit_account_id: u128,
    credit_account_id: u128,  
    user_data: u128,
    reserved: [32]u8,
    timeout: u64,
    ledger: u32,
    code: u16,
    flags: u16,
    amount: u64,
    timestamp: u64 = 0,
};
```

**Comment by jorangreef** [comment]
```zig
pub const TransferFlags = packed struct {
    linked: bool = false,
    pending: bool = false,
    posting: bool = false,
    voiding: bool = false,
    hashlock: bool = false,
    padding: u27 = 0,

    comptime {
        assert(@sizeOf(TransferFlags) == @sizeOf(u16));
    }
};
```

Again, when `posting` is set here, it means the transfer intends to post a `pending` transfer. For one-phase only transfers, this should not be set as it's the default.

The `hashlock` flag replaces `condition/preimage` used by the first- and second-phase transfers respectively, and must still be set for both. i.e. If the `pending` transfer has a `hashlock` with the `condition` stored in the `reserved` field, then the `posting` transfer must also have `hashlock` set in the flags with the `preimage` stored in the `reserved` field.

**Comment by jorangreef** [comment]
@koekiebox what do you think? @wilsonianb and @sentientwaffle it would be great to get your input on this as well.

**Comment by jorangreef** [comment]
Any other ideas if we take a step back and think differently? How could we better support pending/posting transfers where there's slippage? Or where there are multiple micro-postings against a single pending transfer?

I have a feeling we could improve this still for these use-cases, and that generalizing for these would make TB's accounting primitives more powerful while at the same time orthogonal, simple with no overlap across features.

**Comment by wilsonianb** [comment]
re: `posting/voiding`, fwiw the only user-facing two-phase transfers currently present in Rafiki are wallet operators withdrawing liquidity from asset and peer liquidity accounts:
https://github.com/interledger/rafiki/blob/ff68afc9e86cb03436a4ad462efc0824438880c1/packages/backend/src/graphql/schema.graphql#L53-L78
I don't know if we would rename `finalize`/`rollback`.

>add ledger to Transfer (for more safety, to enforce that transfers may only affect accounts in the same ledger).

What I have found a need for is providing the expected transfer `code` when committing, so that I can be sure the transfer I'm dealing with is actually a withdrawal (without having to first do a lookup or storing withdrawal transfer ids outside of TB).

**Comment by sentientwaffle** [comment]
:+1: I like the name `ledger` over `unit`. We just need to be clear in the docs that cross-ledger transfers can still be linked.

But if multi-tenant is a priority, maybe it should be 2 fields? e.g.: `ledger` and `asset`, where transfers must have the same `ledger` field to be linked together.

---

Is `posted/voided` terminology known outside of credit cards? I think ILP's terminology of `fulfilled/rejected` (especially `fulfilled`) is more straightforward and maps better to the actual operations (I like `pending` though).

---

> What I have found a need for is providing the expected transfer `code` when committing, so that I can be sure the transfer I'm dealing with is actually a withdrawal (without having to first do a lookup or storing withdrawal transfer ids outside of TB).

If `code` is always included in transfers (i.e. both prepares and fulfills) then maybe a `code` mismatch between the two could be an error.

---

> How could we better support pending/posting transfers where there's slippage?

Isn't slippage usually just implemented as tweaking the exchange rate of the currency exchange (i.e. no extra transfers)?

> Or where there are multiple micro-postings against a single pending transfer?
> I have a feeling we could improve this still for these use-cases, and that generalizing for these would make TB's accounting primitives more powerful while at the same time orthogonal, simple with no overlap across features.

I'm not sure I understand the use cases mentioned. Is it something like this?: Account `A` prepares a payment of $100 to account `B`. On fulfill, it decides that $99 should go to `B`, and $1 to account `C`.

That could _almost_ work as:
1. Prepare: Create 2-phase transfer of $100 `A → B`.
2. Fulfill: In a transaction of linked transfers, do the following:
    - Cancel the payment in step 1.
    - Create a single-phase transfer of $99 from `A → B`.
    - Create a single-phase transfer of $1 from `A → C`.

But it wouldn't quite work, since the `A → C` transfer could fail (e.g. due to balance limits on `C`).

**Comment by wilsonianb** [comment]
>Or where there are multiple micro-postings against a single pending transfer?

What may end up being useful for tracking Rafiki payment authorization token usage is being able to commit a portion of a transfer and rollback the rest.
It'd be @sentientwaffle 's example :point_up_2: minus the `A → C` transfer

**Comment by jorangreef** [comment]
> What I have found a need for is providing the expected transfer code when committing, so that I can be sure the transfer I'm dealing with is actually a withdrawal (without having to first do a lookup or storing withdrawal transfer ids outside of TB).

@wilsonianb  Yes, this would be great to make available as part of solving this issue (TODO). Would it be fine if the `code` is not checked if it's provided as 0 (i.e. no code)? This would be an opt-out for operators who don't know the code at time of commit and who can't provide it. For operators who do know the code, they can set their code numbering to start at 1. This would mean we don't have to add a flag to trigger the check.

> fwiw the only user-facing two-phase transfers currently present in Rafiki are wallet operators withdrawing liquidity from asset and peer liquidity accounts

I'm glad these are being used. I think the two-phase transfers are also really good for onramping/offramping between systems, or for settlement that takes place externally. i.e. They may not be a 100% use-case, but when they're needed they're convenient.

> 👍 I like the name ledger over unit. We just need to be clear in the docs that cross-ledger transfers can still be linked.

Thanks @sentientwaffle , good point!

> But if multi-tenant is a priority, maybe it should be 2 fields? e.g.: ledger and asset, where transfers must have the same ledger field to be linked together.

Let's keep it as 1 field, since the ledger already incorporates the asset so that all transactions in the ledger must already have the same asset. Doing so also allows up to a 4 billion limit on the number of ledgers, which is great for operators that want to isolate all their tenants in separate ledgers, without having to spin up more than a single cluster.

> Is posted/voided terminology known outside of credit cards?

I have the feeling it is, since people do speak of posting to a ledger.

> I think ILP's terminology of fulfilled/rejected (especially fulfilled) is more straightforward and maps better to the actual operations (I like pending though).

I like `pending` too, and agree that `posting` as a way of committing is not clear, overloading too much on `Account.debits_posted` instead.

I personally find `fulfilled` tough to spell (e.g. Is it three or four l's, according to US or GB spelling?). Just listing all the options:

```
accepting
rejecting
confirming
committing
fulfilling
posting
voiding
```

Maybe we go with `accepting/rejecting`? They are perfect antonyms and line up in the source? So you can "accept or reject a pending transfer". Any other words we can add to the list?

> Isn't slippage usually just implemented as tweaking the exchange rate of the currency exchange (i.e. no extra transfers)?

I was thinking of slippage in my own mind (without much experience) loosely as just whatever is left of a transaction after the transaction has finally happened. So in the case of Rafiki, if I understand correctly, there's a transaction kicked off, but afterwards some of it was lost to intermediaries for some reason (fees etc.). Is my understanding correct?

> What may end up being useful for tracking Rafiki payment authorization token usage is being able to commit a portion of a transfer and rollback the rest.

@wilsonianb , yes, this is what I would really like to explore, to see how we can make TB's two-phase transfers orthogonal enough to support this out of the box. To make it happen, we would need to be able to do one `pending` transfer with an amount of say $10 and then accept sub-amounts of this idempotently up to $10, and then reject other sub-amounts of this idempotently up to $10, rolling back the undecided balance after a timeout.

**Comment by wilsonianb** [comment]
>Would it be fine if the `code` is not checked if it's provided as 0 (i.e. no code)? This would be an opt-out for operators who don't know the code at time of commit and who can't provide it. For operators who do know the code, they can set their code numbering to start at 1.

:+1:

**Comment by sentientwaffle** [comment]
> Maybe we go with accepting/rejecting?

:+1: 

---

> I was thinking of slippage in my own mind (without much experience) loosely as just whatever is left of a transaction after the transaction has finally happened. So in the case of Rafiki, if I understand correctly, there's a transaction kicked off, but afterwards some of it was lost to intermediaries for some reason (fees etc.). Is my understanding correct?

You're correct; I mixed up the terms _slippage_ and _spread_.

In ILP-STREAM, slippage is the amount that the sender is willing to overpay. A larger slippage is naturally more expensive, but it increases the likelihood that the payment succeeds if the exchange rate varies unfavorably over the course of the streamed payment. If the rate doesn't change (or changes favorably) then the slippage is the left over money. It may be returned to the sender's account or claimed by the first connector/Rafiki, depending on the implementation.

**Comment by wilsonianb** [comment]
Would it be possible to make the `timeout` optional on two-phase commit transfers?
That might be useful for the aforementioned Rafiki withdrawals https://github.com/interledger/rafiki/issues/223

**Comment by koekiebox** [comment]
Based on conversation with @jorangreef . Any objections to having the following updated `Transfer` flag names?:

## Transfer Flags:
```
Transfer.flags.posting = true (default) // set to false to indicate pending, this makes a query to retrieve all posted transfers easier
Transfer.flags.post_pending_transfer // post the previously pending transfer
Transfer.flags.void_pending_transfer // rollback a previous pending transfer
```

## Functions:
The following functions will be replacing the `create_transfers / commit_transfers` functions.
```
create_transfers(Transfer[])
```

## Account struct variable names;
```
debits_pending
debits_posted
credits_pending
credits_posted
```

**Comment by jorangreef** [comment]
Thanks @koekiebox

Just a correction that these would also be `Transfer.flags` not functions:

```
Transfer.flags.post_pending_transfer = false
Transfer.flags.void_pending_transfer = false
```

The motivation for `post/void` is to follow the same credit card terminology above. The alternative option is:

```
Transfer.flags.accept_pending_transfer = false
Transfer.flags.reject_pending_transfer = false
```

Although `post_pending_transfer` is more explicit than `accept_pending_transfer` since it shows that what was pending is now about to be posted. "Accepted" doesn't really say as much, it's a new word that doesn't relate to `debits/credits_posted` in the same way.

Any final thoughts on this?

The prepare would then look like this:

```
Transfer.flags.posting = false // Implies the transfer is a pending transfer
```

And the commit would look like this:

```
Transfer.flags.posting = true // The default, also for one-phase transfers that have immediate effect
Transfer.flags.post_pending_transfer = true // Indicates to TB that this is a commit
Transfer.user_data = ID of the pending transfer to commit
```

**Comment by jorangreef** [comment]
> Would it be possible to make the timeout optional on two-phase commit transfers?

@wilsonianb would it be okay instead to set a max-future timeout value? Otherwise, `timeout` might accidentally be left as `0` and then the corresponding pending balance might never be released?

**Comment by koekiebox** [comment]
Thank you @jorangreef . I updated my comment.
Do we have consensus regarding the renaming of the functions from `create_transfers / commit_transfers` to `transfer / post`.
The `post` function will obviously only be applicable to a pending `Transfer`.

**Comment by wilsonianb** [comment]
> > Would it be possible to make the timeout optional on two-phase commit transfers?
> 
> @wilsonianb would it be okay instead to set a max-future timeout value? Otherwise, `timeout` might accidentally be left as `0` and then the corresponding pending balance might never be released?

Maybe transfer queries could help operators identify and resolve such pending transfers.
That said, whether or not Rafiki would actually utilize long/indefinite timeouts is "pending" :wink:
