### ISSUE TITLE
Config: Allocate more messages to avoid stalling Replica's pipeline

### ISSUE THREAD

**Issue by jorangreef** [tigerbeetle/tigerbeetle#69]
At present, our config only allows each replica to have 152 full-sized messages allocated but the pipeline alone (not counting any outgoing send queues even) actually requires 192 messages, so we can deadlock and not have enough messages to make progress if the network reorders all available messages before the first message in the pipeline.

This is because we have an off-by-one when we calculate `config.message_bus_messages_max` since we’re only counting `config.replicas_max` * `prepare_ok` messages in the pipeline, but not also the corresponding single `prepare` message per pipeline slot.

We should also add a comptime assertion to cross-check all these things, for example that `message_bus_messages_max` is sufficient to cover the pipeline plus send queues. Let's add these at the end of `config.zig` also so that any file using the config knows that it's already been checked.

**Comment by sentientwaffle** [comment]
As part of this change, I think the client `request_queue` ring capacity (see https://github.com/coilhq/tigerbeetle/blob/dcaf309abb6e1650f2fb605c14efec3e44cf18a0/src/vsr/client.zig#L70) should be a separate constant defined in `config.zig`. 

Instead of defining the `request_queue` capacity in terms of `message_bus_messages_max`, `message_bus_messages_max` should be defined (in part) in terms of the configurable `request_queue` capacity.

**Comment by sentientwaffle** [comment]
Never mind, replicas don't have a Client, so `message_bus_messages_max` isn't defined in terms of `request_queue`.

**Comment by jorangreef** [comment]
The principle is better though, to define in terms of constants rather than magic numbers.
